-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#0f1511',
  base01 = '#0a0f0c',
  base02 = '#171d19',
  base03 = '#404943',
  base04 = '#c0c9c0',
  base05 = '#dfe4dd',
  base06 = '#2c322d',
  base07 = '#353b36',

  base08 = '#ffb4ab',
  base09 = '#a4cddc',
  base0A = '#b5ccbb',
  base0B = '#91d5ad',
  base0C = '#224c59',
  base0D = '#035233',
  base0E = '#364b3e',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#035233',
  fg = '#0f1511',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#bfe9f9',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#a4cddc',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#b5ccbb',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#266a49',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#0a0f0c',
  fg = '#91d5ad',
})
