-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#181216',
  base01 = '#120c10',
  base02 = '#201a1e',
  base03 = '#4e444a',
  base04 = '#d2c2ca',
  base05 = '#ecdfe5',
  base06 = '#362e33',
  base07 = '#3f373c',

  base08 = '#ffb4ab',
  base09 = '#f5b9a4',
  base0A = '#dcbed1',
  base0B = '#f4b2e2',
  base0C = '#663c2c',
  base0D = '#67355d',
  base0E = '#56404f',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#67355d',
  fg = '#181216',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#ffdbcf',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#f5b9a4',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#dcbed1',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#824c76',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#120c10',
  fg = '#f4b2e2',
})
