-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#121318',
  base01 = '#0d0e13',
  base02 = '#1a1b21',
  base03 = '#45464f',
  base04 = '#c6c6d0',
  base05 = '#e3e1e9',
  base06 = '#2f3036',
  base07 = '#38393f',

  base08 = '#ffb4ab',
  base09 = '#e3badb',
  base0A = '#c1c5dd',
  base0B = '#b5c4ff',
  base0C = '#5b3d57',
  base0D = '#344479',
  base0E = '#414659',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#344479',
  fg = '#121318',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#ffd7f7',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#e3badb',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#c1c5dd',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#4c5c92',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#0d0e13',
  fg = '#b5c4ff',
})
